apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["echo", "nginx Running"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
